/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Programa;

import javax.swing.ImageIcon;

/**
 *
 * @author IngMorales
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        pizza = new javax.swing.JButton();
        tortilla = new javax.swing.JButton();
        pollo = new javax.swing.JButton();
        hamburguesa = new javax.swing.JButton();
        lasaña = new javax.swing.JButton();
        queso = new javax.swing.JButton();
        imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        titulo.setFont(new java.awt.Font("Exotc350 Bd BT", 1, 14)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Recetas La Magica");

        pizza.setText("Pizza");
        pizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pizzaActionPerformed(evt);
            }
        });

        tortilla.setText("Tortilla de Patata");
        tortilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tortillaActionPerformed(evt);
            }
        });

        pollo.setText("Pollo al Vino");
        pollo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                polloActionPerformed(evt);
            }
        });

        hamburguesa.setText("Hamburguesas");
        hamburguesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hamburguesaActionPerformed(evt);
            }
        });

        lasaña.setText("Lasaña");
        lasaña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lasañaActionPerformed(evt);
            }
        });

        queso.setText("Sufle de Queso");
        queso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quesoActionPerformed(evt);
            }
        });

        imagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Programa/logo.jpg"))); // NOI18N
        imagen.setLabelFor(imagen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hamburguesa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lasaña)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(queso))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pizza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tortilla)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pollo))
                            .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pizza)
                    .addComponent(tortilla)
                    .addComponent(pollo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hamburguesa)
                    .addComponent(lasaña)
                    .addComponent(queso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pizzaActionPerformed
        this.setVisible(false);
        pizza nuevo = new pizza();
        nuevo.setVisible(true);
        //System.exit(0);
    }//GEN-LAST:event_pizzaActionPerformed

    private void tortillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tortillaActionPerformed
        this.setVisible(false);
        tortilla nuevo = new tortilla();
        nuevo.setVisible(true);
    }//GEN-LAST:event_tortillaActionPerformed

    private void polloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_polloActionPerformed
        this.setVisible(false);
        pollo nuevo = new pollo();
        nuevo.setVisible(true);
    }//GEN-LAST:event_polloActionPerformed

    private void hamburguesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hamburguesaActionPerformed
        this.setVisible(false);
        hamburguesa nuevo = new hamburguesa();
        nuevo.setVisible(true);
    }//GEN-LAST:event_hamburguesaActionPerformed

    private void lasañaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lasañaActionPerformed
        this.setVisible(false);
        lasaña nuevo = new lasaña();
        nuevo.setVisible(true);
    }//GEN-LAST:event_lasañaActionPerformed

    private void quesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quesoActionPerformed
        this.setVisible(false);
        queso nuevo = new queso();
        nuevo.setVisible(true);
    }//GEN-LAST:event_quesoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hamburguesa;
    private javax.swing.JLabel imagen;
    private javax.swing.JButton lasaña;
    private javax.swing.JButton pizza;
    private javax.swing.JButton pollo;
    private javax.swing.JButton queso;
    private javax.swing.JLabel titulo;
    private javax.swing.JButton tortilla;
    // End of variables declaration//GEN-END:variables
}
